/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const RestaurantInfo = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getMenuSortedByName' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuSortedByPrice' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const RestaurantInfo = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getMenuSortedByName' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuSortedByPrice' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };